seed/Blink/Blink.cpp
seed/Blink/Makefile

Added very simple blink example.

added blink example

---

pod/Encoder/README.md

Updating the Pod Encoder README to correctly describe the behavior when pressing the Encoder.
(The smallest of updates because I'm new here.)

Small update to Pod Encoder Readme.

---

patch/Svf/Svf.cpp

Done in two slightly different ways here.

SVF:  String warning fix

---

patch/PolyOsc/Makefile
patch/PolyOsc/PolyOsc.cpp
patch/PolyOsc/README.md

Three oscillators, mix out, global waveform and master pitch as well as individual pitch.
No v/oct at the moment, currently implemented via mtof.

patch PolyOsc example

---

patch/vco/README.md
patch/vco/ex_vco.cpp

fine tune functionality also added

patchVco readme and oled display

---

patch/verb/README.md
patch/verb/ex_verb.cpp

displayControls, module name, fdbk and LP, README table

Reverb module updates

---

patch/logic/Makefile
patch/logic/README.md
patch/logic/logic.cpp

2 logic gates, and negatable inputs.

Logic gate module

---

pod/ChordMachine/ChordMachine.cpp
pod/ChordMachine/Makefile
pod/ChordMachine/README.md

A simple chord example. 
Cycle through chord types, inversions, and pitch. 
Potential changes: select-able waveform, change colors, different chords, simple filter.

Pod Chord Machine example

---

patch/lfo/Makefile
patch/lfo/README.md
patch/lfo/lfo.cpp

The callback isn't being used at all since it's CV only. If we were to move the LFO updates to the callback we would get accurate frequency results at the cost of being less readable.

Patch Lfo Example

---

patch/FilterBank/FilterBank.cpp
patch/FilterBank/Makefile
patch/FilterBank/README.md

Fixed filter bank example for daisy patch

Filter bank

---

petal/FilterBank/FilterBank.cpp
petal/FilterBank/Makefile
petal/FilterBank/README.md

Moved to 8 filters. 8 leds show filter levels, Purple side is the one being edited.

Petal filterbank port

---

pod/EuclideanDrums/EuclideanDrums.cpp
pod/EuclideanDrums/Makefile
pod/EuclideanDrums/README.md

Won't fill out to full pattern density for some reason.

euclidean drum sequencer

---

field/KeyboardTest/KeyboardTest.cpp
field/KeyboardTest/KeyboardTest.vcxproj
field/KeyboardTest/KeyboardTest.vcxproj.filters
field/KeyboardTest/stm32.props
field/KeyboardTest/stm32.xml

Changed LEDs to show knob values and keyboard indicators.
Updated vsx project stuff to make sure everything worked with latest libdaisy/DaisySP

Keyboard test improvement

---

petal/MultiEffect/Makefile
petal/MultiEffect/MultiEffect.cpp
petal/MultiEffect/README.md

adds wah, changes controls to work better with petal

Port multieffect to petal

---

petal/MultiEffect/MultiEffect.cpp

#112  
Persistent memory will be added with future libdaisy add'n.
Unable to recreate either bug, more info is needed.

petal MultiEffect tweaks / fixes

---

petal/Distortion/Distortion.cpp
petal/Distortion/Makefile
petal/Distortion/README.md

Right now there's a hard clip in series with a soft clip. It might be better to seperate them out into two distortion modes, or remove one of them.

Distortion for petal

---

patch/Sequencer/Makefile
patch/Sequencer/README.md
patch/Sequencer/Sequencer.cpp

Could add some features. Slew, number of steps come to mind.

Patch Step Sequencer

---

ci/build_libs.sh
dist/examples.json

Tested and works fine on Windows. Needs testing still on OSX and Linux.

CI scripts space path bugfix

---

patch/QuadraphonicMixer/Makefile
patch/QuadraphonicMixer/QuadraphonicMixer.cpp
patch/QuadraphonicMixer/README.md
patch/QuadraphonicMixer/quadMixer.h
patch/QuadraphonicMixer/rebuild.sh
patch/QuadraphonicMixer/stereoMixer.h

This review adds a patch example for a quadraphonic/stereo mixer.

Quadraphonic/Stereo Mixer for Patch

---

seed/LCD_HD44780/Makefile
seed/LCD_HD44780/lcd_hd44780.cpp

Added example for LCD HD44780 in Daisy Seed directory.

Added example for LCD HD44780

---

patch/QuadraphonicMixer/README.md

Fix title in QuadraphonicMixer readme.md

---

patch/EnvelopeOscillator/EnvelopeOscillator.cpp
patch/EnvelopeOscillator/Makefile
patch/EnvelopeOscillator/README.md
patch/EnvelopeOscillator/envelope.h
patch/EnvelopeOscillator/oscillator.h
patch/EnvelopeOscillator/rebuild.sh
patch/EnvelopeOscillator/utils.h

I have been an active viewer/contributor to the [BasementState twitch stream](https://www.twitch.tv/basementstate). This oscillator is intended to be used in a tutorial stream sometime in the next couple of months.

Add simple oscillator with built in envelope

---

helper.py

Was using` float** in`.
Now `AudioHandle::InputBuffer in`.
Fixes #197

Change helper.py audio callback to new format

---

helper.py
utils/Template/.vscode/c_cpp_properties.json
utils/Template/.vscode/tasks.json
utils/Template/Makefile
utils/Template/Template.sln
utils/Template/vs/Template.vcxproj
utils/Template/vs/Template.vcxproj.filters

Fix relative path issue.
Allow user specified library location.

Helper feature requests

---

helper.py

update case of daisysp directory from `daisysp` to `DaisySP`

fix casing of daisysp directory

---

field/sampler/Makefile
field/sampler/README.md
field/sampler/samplebuffer.h
field/sampler/sampler.cpp

Adding an example for the daisy field, a very simple sampler with 8 sample slots and dedicated record and play buttons for each. See README.md for more detail.
I'm new to the daisy ecosystem so I'd appreciate someone reviewing my code. This is also my first open source contribution. 
Writing this simple example helped me learn the basics of programming for daisy and taught me how and why to use SDRAM. Hopefully another beginner will find it a helpful reference.
I haven't generated all the project files which other examples seem to have because i'm not sure how and I assume someone at electrosmith has a process for this. If you can point me in the right direction i'm happy to do it.

Add sampler example for daisy field

---

legio/FMOscillator/FMOscillator.cpp

Fixing a slew of control processing bugs that snuck in during refactoring.

FMOscillator Bug Fixes
