- pod/PodMidi/PodMidi-Debug.vgdbsettings
- pod/PodMidi/PodMidi.cpp
added USB printout of incoming notes, and fixed init order. The order of init was allowing the RxFifo to become overflowed before the main loop started.
This is mostly just a bandaid to make sure it works when rebooting with MIDI incoming.
However, this should/can be resolved in the UART Callback handling for Writing to the FIFO in the MIDI object.
> PodMidi fixes

- README.md
This commit changes the links in the main README to point to the current, correct path to the `DaisyExamples` repository.
> Correct git clone links in top-level README.md

- patch/Noise/Makefile
- patch/Noise/Noise.cpp
- patch/Noise/README.md
White noise with two resonant filters. Currently hardcoded to highpass and lowpass, could add a menu to allow for filter selection, but of course bandpass and bandreject can be patched easily from high and lowpass.
> Patch Noise Example

- petal/GeneralFunctionTest/Makefile
- seed/OLED/OLED.cpp
- seed/SDMMC/Makefile
- seed/WavPlayer/Makefile
Removed unnecessary include from `seed/oled` example, and added include flag to `Makefile` for SD card examples to be able to properly see the default ffconf in libdaisy.
> Minor Fixes for folder Reorg in libdaisy

- pod/Looper/Looper.cpp
- pod/StepSequencer/StepSequencer.cpp
- pod/SynthVoice/SynthVoice.cpp
Some pod examples had the buttons mapped backwards to compensate for the backwards defines in libdaisy.
> Fixes pod examples with backwards buttons

- dist/examples.json
- utils/copy_project.py
updated script to work with new template hierarchy and to not process ai/png files.
It now properly checks recursively for things with the Source name, hitting folders like `Source/vs/Source.vcxproj`, etc.
It also now won't try to process files with .png or .ai extensions, and only renames them.
Also updated hardcoded `'/'` character with os.path.sep for consistency and clarity.  I don't think this matters for glob, but could matter down the road for other things.
> Copy Project script update for new Template

- README.md
Update the wiki link from a relative url to an absolute url, as the existing url takes you to `https://github.com/electro-smith/DaisyExamples/blob/master/github.com/electro-smith/DaisyWiki/wiki` which is a 404.
> Fix wiki link by making it an absolute url

- utils/Template/.vscode/c_cpp_properties.json
- utils/Template/.vscode/launch.json
- utils/Template/.vscode/tasks.json
Hi,
Here is a few improvements related to vscode templates:
1. Added few more tasks, with enabled debug and tasks for program with openocd.
2. Debug configuration in launch.json changed to use task with DEBUG=1.
3. Added configuration for macOS to c_cpp_properties.json
> Improvements related to vscode templates 

- patch/EnvelopeOscillator/EnvelopeOscillator.cpp
fixed type names for audio callback to resolve the last thing in #184 (mostly due to my merging PRs out of order)
> EnvelopeOscillator audio type name update

- patch/Nimbus/Nimbus.cpp
Hi
First of all thanks a ton for the awesome new Nimbus firmware. I wanted to port clouds to daisy patch since forever but never found the time. I am so glad you did this!
Currently, when using the encoder to update a parameter <-> input mapping, the parameters get updated during the selection process (i.e. while 'scrolling' through the list). This makes it basically impossible to set a parameter to a fixed value without keeping an active input mapped to it.
This changes the behavior to only update the parameter after exiting the selection process.
Cheers
> Patch/Nimbus: Do not update parameter while changing it

- field/Midi/Midi.cpp
- patch/Midi/Midi.cpp
- pod/Midi/Midi.cpp
Added a MidiHandler and Init to each breakout board (among other things) [here](https://github.com/electro-smith/libDaisy/pull/350).
This PR will update the three relevant examples to use those new handlers.
> Update examples to built in board MidiHandlers

- helper.py
I ran into an issue when trying to create a sample project:
```
python ./helper.py create ../lowstepper/lowstepper_daisy_firmware --board seed
creating new project: ../lowstepper/lowstepper_daisy_firmware for platform: seed
copying /utils/Template to new project: ../lowstepper/lowstepper_daisy_firmware
source directory is not valid.
done
```
I noticed that the line above  (`L151 file_path = pathlib.Path(__file__).as_posix().replace('helper.py', '')`) is returning an empty string, I'm not a python programmer and not sure if that is the expected result. However, this can serve as a temporary fix while the above is investigated. It was sufficient to make the documentation [here](https://github.com/electro-smith/DaisyWiki/wiki/How-To:-Create-a-New-Project) work.
> Fix project create script: Remove file path string concat

- dist/examples.json
- patch/Torus/Makefile
fixed include paths that caused conflict with latest libDaisy.
One of the new libDaisy header files includes cstring, and the compiler didn't like that `dsp/string.h` was in the search path when trying to compile this with that version of libDaisy
> Torus - build fix for upcoming libDaisy changes

- ci/build_examples.py
- rebuild_all.sh
fixed wrong script callout in rebuild all, and fixed printing in new build script to use echo instead of python print.
The python print function was working, but it waited until all system calls were done before writing everything to stdout. Which makes troubleshooting build issues a bit of a pain.
> Minor build script fixes

- .gitignore
- helper.py
- utils/Template/.vscode/c_cpp_properties.json
- utils/Template/.vscode/tasks.json
This update fixes a bug with the existing update (all) command in helper.py, it also makes the copying/updating/creation of Visual Studio+VisualGDB files optional, and non-default.
Also, since `MyProjects/` is called out as the directory for users to try things in the video tutorials and guides, I've added it to the gitignore so that it doesn't have to be manually avoided when contributing new examples back to the community.
> Helper script - making VisualGDB support optional

- helper.py
as the PR states this adds typical audio settings to the default generated project making it easier/clearer for people to update if they want.
At some point I think I'll change the samplerate setting to use float (especially once we can fine tune to ~any target samplerate), but not every board supports the numeric-argument version of the function. So for now it uses the `SaiHandle::Config::SampleRate` enum class version for all boards.
> Added typical audio setting functions to default generated project

- helper.py
Fixes issues when trying to run `helper.py update --include_vgdb`
Also prevents copying of `vs/VisualGDB` file tree that is added by VS VisualGDB when compiling a project.
> fixed update --include_vgdb usage errors

- helper.py
minor typo in helper.py
without this change we get the following
```
~/dev/DaisyExamples$ python3 helper.py create patch/Test --board patch
creating new project: patch/Test for platform: patch
copying utils/Template to new project: patch/Test
done
~/dev/DaisyExamples$ cd patch/Test/
~/dev/DaisyExamples/patch/Test$ make
Makefile:13: ../../libdaisy//core/Makefile: No such file or directory
make: *** No rule to make target '../../libdaisy//core/Makefile'.  Stop.
```
> fix libdaisy casing typo

- seed/Drum/.vscode/tasks.json
- seed/Osc/.vscode/tasks.json
A small fix on the [issue](https://github.com/electro-smith/DaisyExamples/issues/286) I opened a while ago. 
On the `tasks.json` of seed/osc and seed/Drum I changed `"${workspaceFolder}/../../../DaisySP"` to `"${workspaceFolder}/../../DaisySP"`.
> fix: tree structure on tasks

- README.md
- dist/examples.json
Updated README.md for the Support Site migration (e.g., removing links and any mentions of Daisy wiki).
> Update README.md with links to daisy.audio
